### PR TITLE
update bsip40 status

### PR DESCRIPTION
**Pull request by sschiessl-bcp**

### CODE REVIEW

**Comment by pmconrad** [comment]
While you're at it, can you also update BSIPs 43+44 and set their status to "Accepted" on README.md? :-)

**Comment by ryanRfox** [comment]
@pmconrad @sschiessl-bcp I will take care to update the README.md file today with those changes. Also, I will add the Stealth Phase II entries. I intend to stub out entries for the draft BSIPs so we all know what should be assigned next.

**Comment by sschiessl-bcp** [comment]
> While you're at it, can you also update BSIPs 43+44 and set their status to "Accepted" on README.md? :-)

I did it for BSIP40 and will leave the rest to Ryan

**Comment by pmconrad** [comment]
Please roll back the latest commit, otherwise this will produce a conflict with #118. Sorry for the confusion.

**Comment by sschiessl-bcp** [comment]
Done

**Pull request merged**
