### PR TITLE
Added discussion link

### PR DESCRIPTION
**Pull request by cogutvalera**
see https://github.com/bitshares/bitshares-core/issues/758

### CODE REVIEW

**Comment by pmconrad** [comment]
Core #758 is related, but there is no discussion going on. I think we should keep the list of links small, adding every possibly relevant ticket to the BSIP only adds confusion.

**Comment by cogutvalera** [comment]
There are not so many issues related just only 3.

**Comment by ryanRfox** [comment]
My preference will be for a single discussion entry per BSIP. Likely the PR itself. I desire the Description of the  PR to contain references to related discussion topics. This should keep the BSIP document less cluttered and retain the reference materials (elsewhere).

**Comment by TheTaconator** [comment]
@cogutvalera Suggest changing title of this pull request to refer to title of BSIP. Something more descriptive like:

- [Worker Proposal Improvements] Added discussion link
- BSIP 28: Added discussion link
- BSIP on Worker Proposal Improvements: Added discussion link

**Comment by xeroc** [comment]
I agree with @ryanRfox! Fortunately, github issues can be cross-referenced quite easily, if not even automated.

**Comment by pmconrad** [comment]
Closing as per comments.

**Pull request closed without merging**
