### PR TITLE
Update bsip-0072.md

### PR DESCRIPTION
**Pull request by nathanhourt**
This updates the Tanks and Taps description and specification for clarity and correctness based on changes made to the protocol during implementation.

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
What is the gist of the changes?

**Comment by nathanhourt** [comment]
Most of the changes are technical, but there are also some alterations in the abstract and motivation sections to make clearer what Tanks and Taps is and is not. I realized that readers might misunderstand that TNT adds turing complete functionality, so I added a statement that it does not. Changes like that. The [rich diff](https://github.com/bitshares/bsips/pull/268/files?short_path=427ca2c#diff-427ca2cfd57e4e479c2108a1429a70ab) should make those alterations readily evident.

The bulk of the changes is in the specification section, correcting the spec to account for things added and removed during implementation. Most notably, the concept of the `sink` was dropped in favor of the `connection`, and the `deposit_source_restrictor` was removed. These changes were made because I realized during implementation that the TNT structures were too trusting by default and it was easy to create structures that work in the intended fashion, but also in unintended fashions. The updates adjust the defaults so that security is built throughout the structures and not left as an add-on at the end. Created structures should now only work in the intended fashion, no surprises.

**Comment by sschiessl-bcp** [comment]
Looks good to me. Since this BSIP is already created on-chain to be voted on, I would like to ask @abitmore to have a look. I think the changes are not significant enough to warrant a re-voting.

**Comment by nathanhourt** [comment]
Yeah, that was something I considered I'm not sure how much editing BSIPs is a thing... Is there some other way I should go about publishing this update?

**Comment by abitmore** [comment]
Sorry, I haven't made chance to thoroughly review the original BSIP yet, but trusted other reviewers, so please don't expect my opinions on this PR soon.

**Comment by MichelSantos** [comment]
> I think the changes are not significant enough to warrant a re-voting.

For whatever it's worth, I agree that the changes are technical improvements that do not alter the spirit of the specifications.

**Pull request merged**
