### PR TITLE
Add BSIP 33: Maker Orders With Better Prices Take Precedence

### PR DESCRIPTION
**Pull request by abitmore**
BSIP for https://github.com/bitshares/bitshares-core/issues/625 and https://github.com/bitshares/bitshares-core/issues/453.

### CODE REVIEW

**Comment by pmconrad** [comment]
Hm, IMO there's a big overlap between this and BSIP-32, perhaps merge them into one?

**Comment by abitmore** [comment]
IMO they're two things, so I prefer two BSIP's.

By the way I'll reorganize this as well.

**Comment by xeroc** [comment]
Can you maybe clarify to the reader what the difference to #56 (bsip32) is?

**Comment by abitmore** [comment]
@xeroc The title explains.

**Pull request merged**
