### PR TITLE
Initial draft of escrow BSIP (BSIP40)

### PR DESCRIPTION
**Pull request by TheTaconator**
PR for discussion purposes. Initial draft of an escrow feature informational BSIP. Discusses two concepts **so far**. If short on time, I recommend reading "Concept B".

### CODE REVIEW

**Comment by pmconrad** [comment]
Excellent writeup so far!

**Comment by xeroc** [comment]
Referring the issue
https://github.com/bitshares/bsips/issues/44

**Comment by pmconrad** [comment]
Needs a rebase, BSIP 40 has been taken by custom active auth.

**Comment by jmjatlanta** [comment]
Made a pull request that changes filename and adds some tech information. See https://github.com/bitshares/bsips/pull/108

**Comment by TheTaconator** [comment]
Pull request moved to https://github.com/bitshares/bsips/pull/111

**Pull request closed without merging**
