### PR TITLE
Add BSIP 72: Tanks and Taps

### PR DESCRIPTION
**Pull request by nathanhourt**
Pretty render available [here](https://github.com/nathanhourt/bsips/blob/master/bsip-0072.md)

For reference, the issue is https://github.com/bitshares/bsips/issues/178.

### CODE REVIEW

**Comment by abitmore** [comment]
Please don't update README in this PR, but let @ryanRfox do it in another PR. It caused conflicts.

**Comment by abitmore** [comment]
Github does the pretty-render job by itself. Click [`Files changed`](https://github.com/bitshares/bsips/pull/197/files), then click the "rich text" icon for each file.
image
then
image

Why closed the issue? For example, I'd like to discuss potential use cases there, rather than here, we'd focus on specifications and wording in this PR.

**Comment by ryanRfox** [comment]
Thanks for removing the README @nathanhourt. I think this is "done" just looking for an review/approval from @pmconrad @abitmore or another.

**Comment by ryanRfox** [comment]
Oops, checked my notes. @oxarbitrage and/or @christophersanborn was going to make a review/approval of this one. Sorry guys.

**Comment by ryanRfox** [comment]
Great job @nathanhourt on this spec. Appreciate your efforts and the reviews by @oxarbitrage and @pmconrad

**Pull request merged**
